name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  charset: 
    path: ../

dev_dependencies:
  lints: ^2.0.1
