name: charset
description: Multiple charset Encoding and Decoding Library.
version: 1.1.0
homepage:
repository: https://github.com/shirne/charset-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test:
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
